# Generated by Django 5.0.6 on 2024-06-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccess',
            name='role',
            field=models.CharField(choices=[('read_only', 'Read Only'), ('edit', 'Edit'), ('admin', 'Admin')], max_length=10),
        ),
    ]
